name: PR Controller

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  dispatch-private-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Repo Validation
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/org/private-repo/dispatches \
            -d '{
              "event_type": "validate-pr",
              "client_payload": {
                "pr_number": ${{ github.event.pull_request.number }},
                "repo": "${{ github.repository }}"
              }
            }'
