name: PR Controller

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-private-dispatcher:
    name: Call Private Dispatcher
    uses: cosminneamtiu02/mlforge-g5k-security/.github/workflows/dispatcher.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit
