name: PR Controller

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  echo-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Trigger
        run: |
          echo "✅ PR workflow was triggered."
          echo "📦 Repo: ${{ github.repository }}"
          echo "🔢 PR Number: ${{ github.event.pull_request.number }}"
