name: ShellCheck Linter

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: ShellCheck via reviewdog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck with reviewdog
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check  # Shows annotations in PRs
          level: error               # ❗ CI will now fail if violations are found
          pattern: '**/*.sh'         # Scan all .sh files in the repo
